#!/usr/bin/env python3
"""Encode `data/shapes.txt` into `viewer/lib/shapes/canonical-shapes.ts`.

Run from repo root: `python3 tooling/scripts/build_canonical_shapes.py`.

Why this exists: OTP's `patternGeometry` falls back to stop-to-stop
straight lines when its shape lookup misfires (see issue noted in
translate-line.ts). We bake the AVL-derived shapes from `data/shapes.txt`
into a TS module that the backend prefers over OTP's geometry.
"""

import csv
import pathlib


def encode_value(v):
    v = v << 1
    if v < 0:
        v = ~v
    out = []
    while v >= 0x20:
        out.append(chr((0x20 | (v & 0x1F)) + 63))
        v >>= 5
    out.append(chr(v + 63))
    return "".join(out)


def encode_polyline(coords):
    out = []
    plat, plng = 0, 0
    for lat, lng in coords:
        lat_e5 = round(lat * 1e5)
        lng_e5 = round(lng * 1e5)
        out.append(encode_value(lat_e5 - plat))
        out.append(encode_value(lng_e5 - plng))
        plat, plng = lat_e5, lng_e5
    return "".join(out)


repo_root = pathlib.Path(__file__).resolve().parent.parent.parent
shapes_path = repo_root / "data" / "shapes.txt"
out_path = repo_root / "viewer" / "lib" / "shapes" / "canonical-shapes.ts"

shapes = {}
with shapes_path.open() as f:
    for row in csv.DictReader(f):
        sid = row["shape_id"]
        shapes.setdefault(sid, []).append(
            (
                int(row["shape_pt_sequence"]),
                float(row["shape_pt_lat"]),
                float(row["shape_pt_lon"]),
            )
        )

lines = [
    "/* GENERATED by tooling/scripts/build_canonical_shapes.py — do NOT edit. */",
    "",
    "export interface CanonicalShape { directionId: 0 | 1; points: string }",
    "",
    "/**",
    " * Pre-encoded polylines per route shortName. Sourced from",
    " * `data/shapes.txt` (AVL-derived representative shapes). Used in",
    " * `translate-line.ts` as the line-schedule shape source because OTP's",
    " * `patternGeometry` falls back to stop-to-stop straight lines when",
    " * its shape lookup misfires.",
    " *",
    " * Re-run `python3 tooling/scripts/build_canonical_shapes.py` whenever",
    " * `data/shapes.txt` changes.",
    " */",
    "export const CANONICAL_SHAPES: Record<string, CanonicalShape[]> = {",
]
for short in sorted({k.split("-")[0] for k in shapes}):
    lines.append(f"  '{short}': [")
    for suffix, did in [("out", 0), ("in", 1)]:
        sid = f"{short}-{suffix}"
        if sid not in shapes:
            continue
        pts = sorted(shapes[sid], key=lambda x: x[0])
        coords = [(p[1], p[2]) for p in pts]
        encoded = encode_polyline(coords)
        escaped = encoded.replace("\\", "\\\\").replace("'", "\\'")
        lines.append(
            f"    {{ directionId: {did}, points: '{escaped}' }},  // {sid}: {len(coords)} pts"
        )
    lines.append("  ],")
lines.append("};")
lines.append("")

out_path.write_text("\n".join(lines))
print(f"wrote {out_path}")
