/* GENERATED by tooling/scripts/build_canonical_shapes.py — do NOT edit. */

export interface CanonicalShape { directionId: 0 | 1; points: string }

/**
 * Pre-encoded polylines per route shortName. Sourced from
 * `data/shapes.txt` (AVL-derived representative shapes). Used in
 * `translate-line.ts` as the line-schedule shape source because
 * OTP's `patternGeometry` falls back to stop-to-stop straight
 * lines when its shape lookup misfires.
 */
export const CANONICAL_SHAPES: Record<string, CanonicalShape[]> = {
  '3': [
    { directionId: 0, points: 'zpkqE|hb`J????????AC??????????A???????????@A??????????????????????????????????@B@GMqHI_NAeEIgL?u@MoLFa@tI_@uHqJoMg@_ONoJFI@qEqKBM~A_Pr@aFIo@sHwEeCc@oKQEAcNp@C?mDEtKwT????@@J{AeIpMcGpWqKtF??g@B{Fb@UBHtI{F?gQiEkKkBe`@zD' },  // 3-out: 79 pts
    { directionId: 1, points: 'xreqEhq_`JBDpGnQLPlCrHoE`D~@vLa@^y@fPL|CPdN\\dG??ADsAr@gLlEImAQaG??BG`JoO??BCdC{Cs@kC??uGkSwE_MCAsHyRu@cH|S}BdOcBpO|@fEfIzFkD}@qDlNxCD@tJxAVsKzFWD@rIm@dC{InDcPdIcNX}AgJbPbChGJAdLg@??~ZjB}CnSq@pD?\\@HDbOLxKtFZtCG|JArJOxKOjHG`@]aIwJcAWX`L@BB`KDr@FzL?J' },  // 3-in: 75 pts
  ],
  '4': [
    { directionId: 0, points: 'zpkqEbgb`J????????HA??????????AA??????????CF????????AK????????????????CA??????????AA?????CMkE@_H@IEoL??????CYGwL??ASOkJ??y@_PuNNIF{ZZy@a@BwIEUAUpA}MhD_PmCsEEIeEaPvCi@xT|L`OeAQqQkD{YIQsX@EAsIqBcJg@}@d@fElNiBiEaN}VmM_ZyCqHaMtBQJc\\yGIDkGqI' },  // 4-out: 88 pts
    { directionId: 1, points: 'n~fqEpcz_JdGePtF_P@Ei@qF_OgJcErIC@kDjHuEzJsDfC}D}FYg@qHqKgNaH{\\gNlAb@FFlQtHB?bMzEjGxD??nGxIlChEF@tFlIvGlJfG|Il@`AlHtJvMnCbMtBxMlCrClCHDlHtNhOxWbCdD??bHqFzIrBF@|LdC`Ko@fDtRObVoKhA}UwKqFqD}A_LyLrG}QfX^PrHkMhJsLxF{CrEpMbFxT^dLgC|OU`BEjOX`MBF|JA`KCtJQbJG??HA`JIXc@kKuKXhLDFB~LHpLDJ' },  // 4-in: 79 pts
  ],
  '5': [
    { directionId: 0, points: '|thqEli{_J??ACiCkH{LZcGP{NgCeL}HsJoNwFmIqJqNACqCtB' },  // 5-out: 13 pts
    { directionId: 1, points: 'jseqE|{x_J??????HPrBrC`E~F|A~BLJfEpGhInLDBfDhF|N|P@B~IzAdOtClO~ChIxOzKdRxInS|A~AsEuNUyIlMv@lNt@rGbDt@`F{OsB' },  // 5-in: 29 pts
  ],
  '8': [
    { directionId: 0, points: 'zpkqElgb`J????????GY???GK{FE{MBkE@SGkL??KcFEkCCgABg@xHCPDL_@wIwK_MAgPN}MFk@mK????CKdDmX????????????h@wCb@aA}GqP}EuUiKrCeSxYHRfIeM??DKbReQm@mIeLeUoKwQ_C}QcP}EyC~EwH}AG?gPcDCCiI}JeHmKuDqFiEwGqD_Fc@_AkIwLc@i@jGaPdCwGxDqMzAwW??FE' },  // 8-out: 71 pts
    { directionId: 1, points: 'ljfqE`dv_JSzC????}@`O??AFe@dI@FsAdRoPhb@\\|@??lKjOPZrFjI@D|FfI~GbKrXdQ??????~MfCLBpL|B??pYde@lEnW}QbV_FhJlGuJlAoA@CdJ_MbLbEpGlXZxLgCpO??OrS|U`LxFIbDCD?rJIDILyJ??kGkJiZ{]yHgL??uGmXwPsd@{IkOyGkP??yEiT}ToeAcK{e@??yKkj@}BH????????' },  // 8-in: 68 pts
  ],
};
